//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardService
    {
        public int Id { get; set; }
        public Nullable<int> CardId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<double> DiscountPrice { get; set; }
        public string DiscountType { get; set; }
        public Nullable<int> DiscountRatio { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Service Service { get; set; }
    }
}
